### ISSUE TITLE
動作環境について

### ISSUE THREAD

**Issue by undervillage** [tnagae627/BoardSampleApp#1]
2022/1/11現在、アクセス時(※)に下記のエラーが発生しております。
※アクセス先URL：http://localhost:3000/board/index

```
ActionView::Template::Error (Webpacker can't find index.js in /var/www/test/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/js/application-1a3410b5c05d09975bbb.js",
  "application.js.map": "/packs/js/application-1a3410b5c05d09975bbb.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-1a3410b5c05d09975bbb.js"
      ],
      "js.map": [
        "/packs/js/application-1a3410b5c05d09975bbb.js.map"
      ]
    }
  }
}
):
    1: <div id="app"></div>
    2: <%= javascript_pack_tag 'index' %>

app/views/board/index.html.erb:2
```

コードを最新化した後の実行コマンドは下記です。
```
bundle install
bundle exec rails db:migrate
bundle exec rails webpacker:install
bundle exec rails s -b 0.0.0.0
```

実行手順をご教示頂けないでしょうか。

**Comment by tnagae627** [comment]
私の方の環境でコードをクローンしてみて下記のコマンドをルートディレクトリで実施後起動しました。
`
bundle install
bundle exec rails db:migrate
bundle exec rails db:seed
yarn install
bundle exec rails s -b 0.0.0.0
`
違いを正しく理解していないのですが、yarnを使ってフロントエンド側をinstallするとうまくいくようです。

私の方でも上記手順で実施したら同様のエラーが発生しました。

**Comment by undervillage** [comment]
ご確認いただきありがとうございます。

一度ファイル一式を削除し、改めてcloneしたところ動作確認することが出来ました。

一つお伺いしたいのですが、IPアドレスによりユーザーの切り分けを行っていると見受けられるのですが、
現在の構成では「http://localhost:3000/」によるアクセスしか出来ず、
非ログイン状態の別ユーザーの動作確認はどのように行っておりましたでしょうか？

**Comment by tnagae627** [comment]
申し訳ございません、メール通知が来ておらず先程気がつきました。

>現在の構成では「http://localhost:3000/」によるアクセスしか出来ず、
>非ログイン状態の別ユーザーの動作確認はどのように行っておりましたでしょうか？
下記2点行いました。
・seedに自GlobalIP以外の投稿を投入（seedに192.168.0.1のデータを投入しております。）
・スマートフォンとテザリングを行いスマートフォンの回線によるテザリングで別Global IPでの動作確認

**Comment by undervillage** [comment]
なるほど、承知いたしました。
ありがとうございます。
