### ISSUE TITLE
コードレビュー後の動作確認コメント

### ISSUE THREAD

**Issue by undervillage** [tnagae627/BoardSampleApp#2]
プルリクがございませんのでIssueにコメントを残させていただきます。
下記の2点、ご確認頂けましたら幸いです。

・IPアドレスを用いてユーザーの特定行うことはあまりやりません。
　プロクシサーバを使用した場合など、他人と同じ情報になるケースが多いからです。
　→ Cookieを使用した制御に修正して頂くことは可能でしょうか？

・カテゴリのタイトル表示ですが、URLパラメータ「category_name」で表示を利用している理由があればお教えください。
　→ 特に理由が無いようであれば、Categoryテーブルから取得するように修正して頂くことは可能でしょうか？

よろしくお願いいたします。

**Comment by tnagae627** [comment]
>・IPアドレスを用いてユーザーの特定行うことはあまりやりません。
>　プロクシサーバを使用した場合など、他人と同じ情報になるケースが多いからです。
>　→ Cookieを使用した制御に修正して頂くことは可能でしょうか？
こちら承知いたしました。

>・カテゴリのタイトル表示ですが、URLパラメータ「category_name」で表示を利用している理由があればお教えください。
>　→ 特に理由が無いようであれば、Categoryテーブルから取得するように修正して頂くことは可能でしょうか？
元々これは画面のちらつき軽減と通信回数を極力減らそうという意図で元々category_nameをパラメータで渡していたのですが、この程度のデータでしたら確かにサーバサイドで持つ方がよさそうですね。
こちらもあわせて修正させていただきます。

こちらの修正はプルリクであげさせていただきます。

**Comment by undervillage** [comment]
ご対応いただきありがとうございました。
動作のほう、問題ございませんでした。

環境構築について一点、プルリクにコメントさせて頂きました。
https://github.com/tnagae627/BoardSampleApp/pull/3/files#r785888844
